# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/argoproj/argo-workflows/stable/api/openapi-spec/swagger.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class Any(BaseModel):
    type_url: Optional[str] = None
    value: Optional[str] = None
