# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/argoproj/argo-workflows/stable/api/openapi-spec/swagger.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel
from pydantic import Field

from .io.argoproj.events import v1alpha1
from .io.k8s.apimachinery.pkg.apis.meta import v1


class EventSourceDeletedResponse(BaseModel):
    pass


class LogEntry(BaseModel):
    eventName: Optional[str] = Field(
        None, title="optional - the event name (e.g. `example`)"
    )
    eventSourceName: Optional[str] = None
    eventSourceType: Optional[str] = Field(
        None, title="optional - the event source type (e.g. `webhook`)"
    )
    level: Optional[str] = None
    msg: Optional[str] = None
    namespace: Optional[str] = None
    time: Optional[v1.Time] = None


class CreateEventSourceRequest(BaseModel):
    eventSource: Optional[v1alpha1.EventSource] = None
    namespace: Optional[str] = None


class EventSourceWatchEvent(BaseModel):
    object: Optional[v1alpha1.EventSource] = None
    type: Optional[str] = None


class UpdateEventSourceRequest(BaseModel):
    eventSource: Optional[v1alpha1.EventSource] = None
    name: Optional[str] = None
    namespace: Optional[str] = None
